//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DellWarrantyInfo
    {
        public int ID { get; set; }
        public string ServiceTag { get; set; }
        public string WarrantyProvider { get; set; }
        public string WarrantyType { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
    }
}
