//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public InventoryItem()
        {
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int Id { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ItAssetNum { get; set; }
        public string CompAssetNum { get; set; }
        public string Serial1 { get; set; }
        public string Serial2 { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int ItemId { get; set; }
        public int LocationId { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Tracking> Trackings { get; set; }
        public virtual Item Item { get; set; }
        public virtual Location Location { get; set; }
    }
}
